import pg from 'pg';
import 'dotenv/config';
import { currentUserId } from './request-context.js';
const { Pool } = pg;
if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
export const pool = new Pool({ connectionString: process.env.DATABASE_URL, max: Number(process.env.DB_POOL_MAX ?? 10), ssl: process.env.NODE_ENV === 'production' || process.env.DATABASE_URL.includes('neon.tech') ? { rejectUnauthorized: false } : undefined });
export async function query<T = any>(text: string, params: unknown[] = []) { const userId=currentUserId(); if(!userId)return pool.query<T>(text,params); const client=await pool.connect(); try { await client.query('select set_config($1,$2,false)',['app.trace_user_id',userId]); return await client.query<T>(text,params); } finally { try { await client.query('reset app.trace_user_id'); } finally { client.release(); } } }
export async function initDb(){await query(`
create extension if not exists vector;
create table if not exists users(id uuid primary key default gen_random_uuid(),github_id text,github_login text,email text,password_hash text,display_name text,avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists repositories(id uuid primary key default gen_random_uuid(),owner_user_id uuid references users(id) on delete cascade,full_name text not null,name text not null,url text not null,default_branch text not null default 'main',language text not null default 'Unknown',created_at timestamptz not null default now(),last_analyzed_at timestamptz);
alter table repositories add column if not exists owner_user_id uuid references users(id) on delete cascade; alter table repositories drop constraint if exists repositories_full_name_key; create unique index if not exists repositories_owner_full_name_unique_idx on repositories(owner_user_id,full_name); create index if not exists repositories_owner_idx on repositories(owner_user_id,last_analyzed_at desc nulls last);
create or replace function trace_set_repository_owner() returns trigger language plpgsql security definer set search_path=public as $$ declare current_owner uuid; begin current_owner:=nullif(current_setting('app.trace_user_id',true),'')::uuid; if new.owner_user_id is null then if current_owner is null then raise exception 'TRACE_REPOSITORY_OWNER_REQUIRED'; end if; new.owner_user_id:=current_owner; elsif current_owner is null or new.owner_user_id<>current_owner then raise exception 'TRACE_REPOSITORY_OWNER_MISMATCH'; end if; return new; end; $$;
drop trigger if exists trace_repository_owner on repositories; create trigger trace_repository_owner before insert or update on repositories for each row execute function trace_set_repository_owner(); alter table repositories enable row level security; alter table repositories force row level security; drop policy if exists repositories_owner_policy on repositories; create policy repositories_owner_policy on repositories using(owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid) with check(owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid);
create table if not exists investigations(id uuid primary key default gen_random_uuid(),repository_id uuid not null references repositories(id) on delete cascade,status text not null default 'analyzing',pull_request_url text not null,pull_request_number integer not null,title text not null,author text not null,opened_at timestamptz,head_branch text not null,base_branch text not null,head_sha text,base_sha text,additions integer not null default 0,deletions integer not null default 0,analysis_seconds integer not null default 0,result jsonb,error text,created_at timestamptz not null default now(),analyzed_at timestamptz);
alter table investigations add column if not exists head_sha text; alter table investigations add column if not exists base_sha text; create index if not exists investigations_repo_idx on investigations(repository_id,created_at desc); create index if not exists investigations_status_idx on investigations(status); create unique index if not exists investigations_active_pr_unique_idx on investigations(repository_id,pull_request_number) where status='analyzing'; alter table investigations enable row level security; alter table investigations force row level security; drop policy if exists investigations_owner_policy on investigations; create policy investigations_owner_policy on investigations using(exists(select 1 from repositories r where r.id=investigations.repository_id and r.owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid)) with check(exists(select 1 from repositories r where r.id=investigations.repository_id and r.owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid));
create table if not exists analysis_events(id bigserial primary key,investigation_id uuid not null references investigations(id) on delete cascade,stage_id text not null,label text not null,detail text,status text not null,created_at timestamptz not null default now(),unique(investigation_id,stage_id)); create index if not exists analysis_events_inv_idx on analysis_events(investigation_id,id); alter table analysis_events enable row level security; alter table analysis_events force row level security; drop policy if exists analysis_events_owner_policy on analysis_events; create policy analysis_events_owner_policy on analysis_events using(exists(select 1 from investigations i join repositories r on r.id=i.repository_id where i.id=analysis_events.investigation_id and r.owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid)) with check(exists(select 1 from investigations i join repositories r on r.id=i.repository_id where i.id=analysis_events.investigation_id and r.owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid));
create table if not exists app_settings(id uuid primary key default gen_random_uuid(),user_id uuid references users(id) on delete cascade,analysis_depth text not null default 'standard',risk_threshold integer not null default 60,notify_high_risk boolean not null default true,api_key_hash text,api_key_last4 text,created_at timestamptz not null default now(),updated_at timestamptz not null default now()); alter table app_settings add column if not exists user_id uuid references users(id) on delete cascade; alter table app_settings alter column id drop default; alter table app_settings alter column id type uuid using gen_random_uuid(); create unique index if not exists app_settings_user_unique_idx on app_settings(user_id) where user_id is not null; create index if not exists app_settings_user_idx on app_settings(user_id); update app_settings s set user_id=u.id from users u where s.user_id is null and u.id=(select id from users order by created_at limit 1); alter table app_settings enable row level security; alter table app_settings force row level security; drop policy if exists app_settings_owner_policy on app_settings; create policy app_settings_owner_policy on app_settings using(user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid) with check(user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid);
create or replace function trace_set_settings_owner() returns trigger language plpgsql security definer set search_path=public as $$ declare current_owner uuid; begin current_owner:=nullif(current_setting('app.trace_user_id',true),'')::uuid; if new.user_id is null then if current_owner is null then raise exception 'TRACE_SETTINGS_OWNER_REQUIRED'; end if; new.user_id:=current_owner; elsif current_owner is null or new.user_id<>current_owner then raise exception 'TRACE_SETTINGS_OWNER_MISMATCH'; end if; return new; end; $$; drop trigger if exists trace_settings_owner on app_settings; create trigger trace_settings_owner before insert or update on app_settings for each row execute function trace_set_settings_owner();
create table if not exists notifications(id bigserial primary key,owner_user_id uuid references users(id) on delete cascade,type text not null,title text not null,message text not null,investigation_id uuid references investigations(id) on delete cascade,read_at timestamptz,created_at timestamptz not null default now()); alter table notifications add column if not exists owner_user_id uuid references users(id) on delete cascade; create index if not exists notifications_owner_created_idx on notifications(owner_user_id,created_at desc); alter table notifications enable row level security; alter table notifications force row level security; drop policy if exists notifications_owner_policy on notifications; create policy notifications_owner_policy on notifications using(owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid) with check(owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid);
create or replace function trace_set_notification_owner() returns trigger language plpgsql security definer set search_path=public as $$ declare current_owner uuid; begin current_owner:=nullif(current_setting('app.trace_user_id',true),'')::uuid; if new.owner_user_id is null then if current_owner is null then raise exception 'TRACE_NOTIFICATION_OWNER_REQUIRED'; end if; new.owner_user_id:=current_owner; elsif current_owner is null or new.owner_user_id<>current_owner then raise exception 'TRACE_NOTIFICATION_OWNER_MISMATCH'; end if; return new; end; $$; drop trigger if exists trace_notification_owner on notifications; create trigger trace_notification_owner before insert or update on notifications for each row execute function trace_set_notification_owner();
create table if not exists semantic_chunks(id uuid primary key default gen_random_uuid(),owner_user_id uuid not null references users(id) on delete cascade,repository_id uuid references repositories(id) on delete cascade,source_type text not null,source_id text,content text not null,path text,start_line integer,end_line integer,metadata jsonb not null default '{}'::jsonb,embedding vector(1536),created_at timestamptz not null default now(),updated_at timestamptz not null default now()); create index if not exists semantic_chunks_owner_repo_idx on semantic_chunks(owner_user_id,repository_id); create index if not exists semantic_chunks_source_idx on semantic_chunks(source_type,source_id); alter table semantic_chunks enable row level security; alter table semantic_chunks force row level security; drop policy if exists semantic_chunks_owner_policy on semantic_chunks; create policy semantic_chunks_owner_policy on semantic_chunks using(owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid) with check(owner_user_id=nullif(current_setting('app.trace_user_id',true),'')::uuid);
`);}
