import type { Server as HttpServer } from 'node:http';
import { createHmac, timingSafeEqual } from 'node:crypto';
import { WebSocketServer, WebSocket } from 'ws';
import { query } from './db.js';
import { currentUserId, withPrincipal } from './request-context.js';
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;const TOKEN_TTL_SECONDS=15*60;const subscribers=new Map<string,Set<WebSocket>>();let wss:WebSocketServer|null=null;
function secret(){const value=process.env.REALTIME_SECRET;if(!value||value.length<32)throw new Error('REALTIME_SECRET must be at least 32 characters');return value;}
export function issueRealtimeToken(investigationId:string,userId=currentUserId()||''){if(!UUID_RE.test(investigationId)||!UUID_RE.test(userId))throw new Error('Invalid realtime identity');const exp=Math.floor(Date.now()/1000)+TOKEN_TTL_SECONDS;const payload=`${investigationId}.${userId}.${exp}`;const signature=createHmac('sha256',secret()).update(payload).digest('base64url');return`${payload}.${signature}`;}
function verifyRealtimeToken(token:string|null,investigationId:string){if(!token)return null;const parts=token.split('.');if(parts.length!==4||parts[0]!==investigationId||!UUID_RE.test(parts[1]))return null;const exp=Number(parts[2]);if(!Number.isSafeInteger(exp)||exp<Math.floor(Date.now()/1000))return null;const expected=createHmac('sha256',secret()).update(`${parts[0]}.${parts[1]}.${parts[2]}`).digest('base64url');const a=Buffer.from(parts[3]);const b=Buffer.from(expected);return a.length===b.length&&timingSafeEqual(a,b)?parts[1]:null;}
export function attachRealtime(server:HttpServer){wss=new WebSocketServer({noServer:true,maxPayload:4096});server.on('upgrade',(request,socket,head)=>{try{const origin=request.headers.origin;const allowed=(process.env.CORS_ORIGIN||'').split(',').map(v=>v.trim()).filter(Boolean);if(process.env.NODE_ENV==='production'&&(!origin||!allowed.includes(origin)))return socket.destroy();if(origin&&allowed.length&&!allowed.includes(origin))return socket.destroy();const url=new URL(request.url||'/','http://'+(request.headers.host||'localhost'));const match=url.pathname.match(/^\/ws\/investigations\/([^/]+)$/);if(!match||!UUID_RE.test(match[1]))return socket.destroy();const userId=verifyRealtimeToken(url.searchParams.get('token'),match[1]);if(!userId)return socket.destroy();wss!.handleUpgrade(request,socket,head,ws=>wss!.emit('connection',ws,match[1],userId));}catch{socket.destroy();}});wss.on('connection',async(ws:WebSocket,investigationId:string,userId:string)=>{let set=subscribers.get(investigationId);if(!set)subscribers.set(investigationId,(set=new Set()));set.add(ws);ws.on('close',()=>{set!.delete(ws);if(!set!.size)subscribers.delete(investigationId);});ws.on('error',()=>ws.close());try{await withPrincipal({userId},async()=>{const{rows}=await query<any>('select i.id from investigations i where i.id=$1',[investigationId]);if(!rows[0]){ws.close();return;}const{rows:events}=await query<any>('select stage_id id,label,detail,status from analysis_events where investigation_id=$1 order by id',[investigationId]);if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'snapshot',investigationId,events}));});}catch{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type:'error',message:'Unable to load analysis progress'}));}});}
export function publishInvestigation(investigationId:string,event:unknown){const set=subscribers.get(investigationId);if(!set)return;const payload=JSON.stringify(event);for(const ws of set)if(ws.readyState===WebSocket.OPEN)ws.send(payload);}
