import crypto from 'node:crypto';
import type { Express } from 'express';
import { query } from './db.js';
import { fetchRepositoryContext, parseRepositoryUrl } from './github.js';
import { getGithubAccessToken } from './auth.js';
import { currentUserId } from './request-context.js';

export type AnalysisDepth = 'fast' | 'standard' | 'deep';
const DEFAULTS = { analysisDepth: 'standard' as AnalysisDepth, riskThreshold: 60, notifyHighRisk: true };
function generateApiKey() { return `trace_sk_live_${crypto.randomBytes(24).toString('hex')}`; }
function hashApiKey(key: string) { return crypto.createHash('sha256').update(key).digest('hex'); }
function maskKey(last4: string | null) { return last4 ? `trace_sk_live_••••••••••••••••••••${last4}` : 'Not generated'; }
function requireUserId() { const id = currentUserId(); if (!id) throw new Error('UNAUTHORIZED'); return id; }
function githubHeaders(token: string) { return { accept: 'application/vnd.github+json', authorization: `Bearer ${token}`, 'x-github-api-version': '2022-11-28' }; }
async function githubList(path: string, token: string, maxPages = 20) { const all: any[] = []; for (let page = 1; page <= maxPages; page++) { const response = await fetch(`https://api.github.com${path}${path.includes('?') ? '&' : '?'}per_page=100&page=${page}`, { headers: githubHeaders(token) }); if (!response.ok) { if (response.status === 401) throw new Error('GITHUB_AUTH_REQUIRED'); if (response.status === 403 && response.headers.get('x-ratelimit-remaining') === '0') throw new Error('GITHUB_RATE_LIMITED'); throw new Error(`GITHUB_UPSTREAM_ERROR_${response.status}`); } const batch = await response.json() as any[]; all.push(...batch); if (batch.length < 100) break; } return all; }
export async function verifyApiKey(key: string) { if (!key) return false; const userId = currentUserId(); if (!userId) return false; const { rows } = await query<any>('select api_key_hash from app_settings where user_id=$1 limit 1', [userId]); const stored = rows[0]?.api_key_hash; if (!stored || stored.length !== 64) return false; return crypto.timingSafeEqual(Buffer.from(stored, 'utf8'), Buffer.from(hashApiKey(key), 'utf8')); }
export async function getSettings() { const userId = requireUserId(); await query(`insert into app_settings(user_id,analysis_depth,risk_threshold,notify_high_risk) values($1,$2,$3,$4) on conflict(user_id) where user_id is not null do nothing`, [userId, DEFAULTS.analysisDepth, DEFAULTS.riskThreshold, DEFAULTS.notifyHighRisk]); const { rows } = await query<any>('select * from app_settings where user_id=$1 limit 1', [userId]); const s = rows[0]; return { analysisDepth: s.analysis_depth as AnalysisDepth, riskThreshold: Number(s.risk_threshold), notifyHighRisk: Boolean(s.notify_high_risk), apiKeyMasked: maskKey(s.api_key_last4) }; }
export async function registerSettingsRoutes(app: Express) {
  app.get('/api/v1/settings', async (_req, res) => { try { res.json(await getSettings()); } catch (e) { if (e instanceof Error && e.message === 'UNAUTHORIZED') return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Authentication required.' } }); res.status(500).json({ error: { code: 'SETTINGS_LOAD_FAILED', message: 'Failed to load settings.' } }); } });
  app.put('/api/v1/settings', async (req, res) => { try { const userId = requireUserId(); const depth = String(req.body?.analysisDepth || DEFAULTS.analysisDepth) as AnalysisDepth; const threshold = Number(req.body?.riskThreshold ?? DEFAULTS.riskThreshold); const notify = Boolean(req.body?.notifyHighRisk ?? DEFAULTS.notifyHighRisk); if (!['fast','standard','deep'].includes(depth)) return res.status(400).json({ error: { code: 'INVALID_ANALYSIS_DEPTH', message: 'analysisDepth must be fast, standard or deep' } }); if (!Number.isFinite(threshold) || threshold < 0 || threshold > 100) return res.status(400).json({ error: { code: 'INVALID_RISK_THRESHOLD', message: 'riskThreshold must be between 0 and 100' } }); await query(`insert into app_settings(user_id,analysis_depth,risk_threshold,notify_high_risk) values($1,$2,$3,$4) on conflict(user_id) where user_id is not null do update set analysis_depth=excluded.analysis_depth,risk_threshold=excluded.risk_threshold,notify_high_risk=excluded.notify_high_risk,updated_at=now()`, [userId, depth, Math.round(threshold), notify]); res.json(await getSettings()); } catch (e) { if (e instanceof Error && e.message === 'UNAUTHORIZED') return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Authentication required.' } }); res.status(500).json({ error: { code: 'SETTINGS_SAVE_FAILED', message: 'Failed to save settings.' } }); } });
  app.post('/api/v1/settings/api-key/rotate', async (_req, res) => { try { const userId = requireUserId(); const key = generateApiKey(); await query(`insert into app_settings(user_id,api_key_hash,api_key_last4) values($1,$2,$3) on conflict(user_id) where user_id is not null do update set api_key_hash=excluded.api_key_hash,api_key_last4=excluded.api_key_last4,updated_at=now()`, [userId, hashApiKey(key), key.slice(-4)]); res.status(201).json({ key, masked: maskKey(key.slice(-4)) }); } catch (e) { if (e instanceof Error && e.message === 'UNAUTHORIZED') return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Authentication required.' } }); res.status(500).json({ error: { code: 'API_KEY_ROTATION_FAILED', message: 'Failed to rotate API key.' } }); } });
  app.get('/api/v1/github/connection', async (_req, res) => { try { const userId = requireUserId(); const token = await getGithubAccessToken(userId); if (!token) return res.json({ connected: false, account: null, repositoryCount: 0, manageUrl: '/api/v1/auth/github' }); const headers = githubHeaders(token); const response = await fetch('https://api.github.com/user', { headers }); if (!response.ok) return res.json({ connected: false, account: null, repositoryCount: 0, manageUrl: '/api/v1/auth/github' }); const user: any = await response.json(); const reposResponse = await fetch('https://api.github.com/user/repos?per_page=1', { headers }); const link = reposResponse.headers.get('link') || ''; const match = link.match(/page=(\d+)>; rel="last"/); const repositoryCount = match ? Number(match[1]) : reposResponse.ok ? 1 : 0; res.json({ connected: true, account: user.login, repositoryCount, manageUrl: '/api/v1/auth/github' }); } catch (e) { if (e instanceof Error && e.message === 'UNAUTHORIZED') return res.status(401).json({ error: { code: 'UNAUTHORIZED', message: 'Authentication required.' } }); res.json({ connected: false, account: null, repositoryCount: 0, manageUrl: '/api/v1/auth/github' }); } });
  app.get('/api/v1/github/repositories', async (req, res) => { try { const userId = requireUserId(); const token = await getGithubAccessToken(userId); if (!token) return res.status(401).json({ error: { code: 'GITHUB_AUTH_REQUIRED', message: 'Connect GitHub to browse repositories.' } }); const q = String(req.query.q || '').trim().toLowerCase(); const repos = await githubList('/user/repos?sort=updated&direction=desc', token); const filtered = q ? repos.filter((r: any) => `${r.full_name} ${r.name} ${r.description || ''}`.toLowerCase().includes(q)) : repos; res.json(filtered.map((r: any) => ({ id: String(r.id), name: r.name, fullName: r.full_name, url: r.html_url, defaultBranch: r.default_branch || 'main', language: r.language || 'Unknown', private: Boolean(r.private), updatedAt: r.updated_at, description: r.description || null }))); } catch (e) { const message = e instanceof Error ? e.message : 'Failed to load repositories.'; const status = message === 'GITHUB_AUTH_REQUIRED' ? 401 : message === 'GITHUB_RATE_LIMITED' ? 429 : 500; res.status(status).json({ error: { code: message.startsWith('GITHUB_') ? message : 'GITHUB_REPOSITORIES_LOAD_FAILED', message: message === 'GITHUB_AUTH_REQUIRED' ? 'Connect GitHub to browse repositories.' : message === 'GITHUB_RATE_LIMITED' ? 'GitHub rate limit reached. Try again later.' : 'Failed to load GitHub repositories.' } }); } });
  app.get('/api/v1/github/repositories/:owner/:repo/pulls', async (req, res) => { try { const userId = requireUserId(); const token = await getGithubAccessToken(userId); if (!token) return res.status(401).json({ error: { code: 'GITHUB_AUTH_REQUIRED', message: 'Connect GitHub to browse pull requests.' } }); const owner = encodeURIComponent(req.params.owner); const repo = encodeURIComponent(req.params.repo); const state = req.query.state === 'closed' || req.query.state === 'all' ? String(req.query.state) : 'open'; const prs = await githubList(`/repos/${owner}/${repo}/pulls?state=${encodeURIComponent(state)}&sort=updated&direction=desc`, token, 10); const q = String(req.query.q || '').trim().toLowerCase(); const filtered = q ? prs.filter((pr: any) => `${pr.title} #${pr.number} ${pr.user?.login || ''}`.toLowerCase().includes(q)) : prs; res.json(filtered.map((pr: any) => ({ number: pr.number, title: pr.title, author: pr.user?.login || 'unknown', url: pr.html_url, state: pr.state, draft: Boolean(pr.draft), updatedAt: pr.updated_at, additions: pr.additions ?? 0, deletions: pr.deletions ?? 0, changedFiles: pr.changed_files ?? 0 }))); } catch (e) { const message = e instanceof Error ? e.message : 'Failed to load pull requests.'; const status = message === 'GITHUB_AUTH_REQUIRED' ? 401 : message === 'GITHUB_RATE_LIMITED' ? 429 : 500; res.status(status).json({ error: { code: message.startsWith('GITHUB_') ? message : 'GITHUB_PRS_LOAD_FAILED', message: message === 'GITHUB_AUTH_REQUIRED' ? 'Connect GitHub to browse pull requests.' : message === 'GITHUB_RATE_LIMITED' ? 'GitHub rate limit reached. Try again later.' : 'Failed to load pull requests.' } }); } });
  app.post('/api/v1/repositories', async (req, res) => { try { const userId = requireUserId(); const url = String(req.body?.url || ''); const parsed = parseRepositoryUrl(url); const repo = await fetchRepositoryContext(url); const result = await query<any>(`insert into repositories(owner_user_id,full_name,name,url,default_branch,language) values($1,$2,$3,$4,$5,$6) on conflict(owner_user_id,full_name) do update set name=excluded.name,url=excluded.url,default_branch=excluded.default_branch,language=excluded.language returning *`, [userId, `${parsed.owner}/${parsed.repo}`, parsed.repo, repo.html_url, repo.default_branch || 'main', repo.language || 'Unknown']); res.status(201).json(result.rows[0]); } catch (e) { const message = e instanceof Error ? e.message : 'Unable to add repository'; const code = message.startsWith('GITHUB_') ? message : 'REPOSITORY_ADD_FAILED'; const status = code === 'GITHUB_AUTH_REQUIRED' ? 401 : code === 'GITHUB_PERMISSION_DENIED' ? 403 : code === 'GITHUB_REPOSITORY_NOT_FOUND' ? 404 : 400; res.status(status).json({ error: { code, message: code === 'GITHUB_AUTH_REQUIRED' ? 'Connect GitHub before adding repositories.' : code === 'GITHUB_PERMISSION_DENIED' ? 'GitHub denied access to this repository.' : code === 'GITHUB_REPOSITORY_NOT_FOUND' ? 'Repository not found or not accessible.' : message } }); } });
  app.get('/api/v1/notifications', async (_req, res) => { const { rows } = await query<any>(`select id,type,title,message,investigation_id,read_at,created_at from notifications order by created_at desc limit 50`); res.json(rows); });
  app.patch('/api/v1/notifications/:id/read', async (req, res) => { const { rows } = await query<any>(`update notifications set read_at=coalesce(read_at,now()) where id=$1 returning id,type,title,message,investigation_id,read_at,created_at`, [req.params.id]); if (!rows[0]) return res.status(404).json({ error: { code: 'NOTIFICATION_NOT_FOUND', message: 'Notification not found' } }); res.json(rows[0]); });
}
