/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as InvestigationsRouteImport } from './routes/investigations'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InvestigationIdRouteImport } from './routes/investigation.$id'
import { Route as RepositoriesIndexRouteImport } from './routes/repositories.index'
import { Route as RepositoriesIdRouteImport } from './routes/repositories.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationsRoute = InvestigationsRouteImport.update({
  id: '/investigations',
  path: '/investigations',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestigationIdRoute = InvestigationIdRouteImport.update({
  id: '/investigation/$id',
  path: '/investigation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIndexRoute = RepositoriesIndexRouteImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesIdRoute = RepositoriesIdRouteImport.update({
  id: '/repositories/$id',
  path: '/repositories/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/repositories': typeof RepositoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/investigations': typeof InvestigationsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/investigation/$id': typeof InvestigationIdRoute
  '/repositories/$id': typeof RepositoriesIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/investigations'
    | '/login'
    | '/settings'
    | '/investigation/$id'
    | '/repositories/$id'
    | '/repositories/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/investigations'
    | '/login'
    | '/settings'
    | '/investigation/$id'
    | '/repositories/$id'
    | '/repositories'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/investigations'
    | '/login'
    | '/settings'
    | '/investigation/$id'
    | '/repositories/$id'
    | '/repositories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  InvestigationsRoute: typeof InvestigationsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  InvestigationIdRoute: typeof InvestigationIdRoute
  RepositoriesIdRoute: typeof RepositoriesIdRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigations': {
      id: '/investigations'
      path: '/investigations'
      fullPath: '/investigations'
      preLoaderRoute: typeof InvestigationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investigation/$id': {
      id: '/investigation/$id'
      path: '/investigation/$id'
      fullPath: '/investigation/$id'
      preLoaderRoute: typeof InvestigationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories/'
      preLoaderRoute: typeof RepositoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$id': {
      id: '/repositories/$id'
      path: '/repositories/$id'
      fullPath: '/repositories/$id'
      preLoaderRoute: typeof RepositoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  InvestigationsRoute: InvestigationsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  InvestigationIdRoute: InvestigationIdRoute,
  RepositoriesIdRoute: RepositoriesIdRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
